language: python
python:
  - "3.6"      # detault Python on Travis CI as of 2019
  - "3.7"
before_install:
  - sudo apt-get install -qq exiftool
  - pip install codecov
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .
  - pip install flake8
  - pip install pytest
  - pip install pytest-cov
script:
  - flake8 *.py
  - pytest
after_success:
  - codecov
