language: python
python:
  - "3.6"      # detault Python on Travis CI as of 2019
  - "3.7"
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .
  - pip install flake8
  - pip install pytest
script:
  - flake8 *.py
  - pytest
