name: Install and test
on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        python: [ '3.6', '3.7' ]
    name: Python ${{ matrix.python }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: sudo apt-get install -qq exiftool
      - run: python -m venv create venv
      - run: . ./venv/bin/activate
      - run: pip install .
      - run: pip install flake8
      - run: pip install pytest
      - run: flake8 *.py
      - run: pytest
