name: Main workflow
on:
  push:
    paths:
    - '*'
    - 'photo_backup/*'
    - 'tests/*'
    - '.github/workflows/*'
    - '!README.md'
    - '!.travis.yml'
    - '!.gitignore'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [ '3.8', '3.9' ]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: python -m venv create venv
      - run: . ./venv/bin/activate
      - run: pip install .
      - run: pip install flake8
      - run: pip install pytest
      - run: pip install codecov
      - run: pip install pytest-cov
      - run: flake8 -v photo_backup/*.py tests/*.py
      - run: pytest --cov=./
      - run: coverage xml
      - uses: codecov/codecov-action@v2
